version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - volumensito:/var/lib/mysql
    networks:
      - backend

  categoria:
    image: jaguacoa2/jq-categoria:latest
    container_name: jq-categoria
    restart: unless-stopped
    ports:
      - "8084:8084"
    environment:
      PORT: 8084
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: test
      DB_USER: root
      DB_PASSWORD: admin123
    depends_on:
      - mysql
    networks:
      - backend

  producto:
    image: jaguacoa2/jq-producto:latest
    container_name: jq-producto
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      PORT: 8082
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: test
      DB_USER: root
      DB_PASSWORD: admin123
    depends_on:
      - mysql
    networks:
      - backend

  catalogo-frontend:
    image: jaguacoa2/jq-angular:latest
    container_name: jq-angular
    restart: unless-stopped
    ports:
      - "8080:80" 
    networks:
      - backend

volumes:
  volumensito:
    external: true

networks:
  backend:
    driver: bridge
